spring.application.name=10_New_JPA_Repository_employee_

spring.datasource.url=jdbc:mysql://localhost:3306/student_jpa_db

spring.datasource.username=root

spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true